bigquery:
  target: default
  outputs:
    default:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DBT_DATASET') }}"
      threads: 1
      keyfile: /tmp/bigquery/keyfile.json
      <optional_config>: <value>